### ISSUE TITLE
frail url mutation for tar ball snippets

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/rosinstall_generator#18]
I just ran into this problem where the rosinstall snippets generated for some packages in indigo are invalid. For example, `eigen_stl_containers`'s snippet:

```
% rosinstall_generator eigen_stl_containers --rosdistro indigo --tar
- tar:
    local-name: eigen_stl_containers
    uri: https://github.com/ros-gbp/eigen_stl_containers-release
    version: eigen_stl_containers-rel-release-indigo-eigen_stl_containers-0.1.4-0
```

You can see here that the `uri` is not pointing to a tarball. By comparison a valid snippet is:

```
% rosinstall_generator eigen_stl_containers --tar
Using ROS_DISTRO: hydro
- tar:
    local-name: eigen_stl_containers
    uri: https://github.com/ros-gbp/eigen_stl_containers-release/archive/release/hydro/eigen_stl_containers/0.1.4-0.tar.gz
    version: eigen_stl_containers-release-release-hydro-eigen_stl_containers-0.1.4-0
```

I have determined that this is because the entry in the `distribution.yaml` file for Indigo is missing the `.git` extension:

``` yaml
  eigen_stl_containers:
    release:
      tags:
        release: release/indigo/{package}/{version}
      url: https://github.com/ros-gbp/eigen_stl_containers-release
      version: 0.1.4-0
```

I have opened a pull request to fix those missing extensions and add a check for rosdistro CI to check for them here:

https://github.com/ros/rosdistro/pull/3204/files

Ultimately, even if we fix the missing extensions in the rosdistro file, this line of code:

https://github.com/ros-infrastructure/rosinstall_generator/blob/master/src/rosinstall_generator/distro.py#L135

Is pretty fragile. We should at least assert that it ends with `.git` and fail because we cannot convert it otherwise.
